#ifndef CONTROL_PAGE_H
#define CONTROL_PAGE_H

static String render_control_html_v28c(){
  String s=F(
"<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>HMK 智能控制</title>"

"<!--"
"【此次顯示溫度邏輯原理（只影響手機頁顯示，不改設備控制/回傳數值）】"
"1) 正常：T實 <= T設 → 顯示 = T實。"
"2) 升溫時不顯示超過設定 → 顯示 = min(T實, T設)。"
"3) 當偵測到『設定溫下降』且當下顯示 > 新T設、並且 T實仍 > 新T設："
"   (a) diff=T實-T設 > 3：顯示以上次調整前顯示值為上限，但只要T實下降，顯示也跟著下降（不因新設定瞬降）。"
"   (b) 當 diff <= 3：需連續30秒內無降溫，才開始每30秒顯示下降1°C，直到顯示 = T設。"
"   (c) 一旦 T實 <= T設 → 回到正常（顯示 = T實），並結束修正流程。"
"4) 設定溫上調且目標顯示高於目前顯示時：顯示每30秒上升1°C，直到追上目標顯示(min(T實,T設))。"
"-->"

"<style>"
":root{--r:18px;--gap:clamp(8px,3vw,16px);--pad:clamp(10px,4vw,18px);"
"--fs:clamp(16px,4vw,22px);--fsTitle:clamp(20px,6vw,30px);--btnH:clamp(58px,11vw,74px);"
"--red:#e53935;--green:#1aa94a;--blue:#1877f2;--gray:#555;--shadow:0 6px 14px rgba(0,0,0,.25)}"
"body{margin:0;background:linear-gradient(160deg,#f4f8ff,#eaf0ff);font-family:'Noto Sans TC',Arial;"
"font-size:var(--fs);color:#222;display:flex;justify-content:center;align-items:flex-start;min-height:100vh;padding-top:20px}"
".card{background:#fff;border-radius:calc(var(--r)+6px);box-shadow:0 8px 25px rgba(0,0,0,.12);padding:var(--pad);width:90%;max-width:420px;text-align:center}"
"h3{font-size:var(--fsTitle);margin-bottom:var(--gap);color:#0f244d;text-shadow:0 2px 4px rgba(0,0,0,.15)}"
".statusText{font-size:clamp(20px,5vw,28px);font-weight:800;margin-bottom:6px}"
".heatText{font-size:clamp(16px,4vw,22px);font-weight:800;margin-top:2px;margin-bottom:8px}"
".statusOn{color:var(--green)} .statusOff{color:var(--red)} .statusTimer{color:var(--blue)}"
".heatOn{color:#e67e22}.heatOff{color:#6b7280}.heatWait{color:#94a3b8}"
".led{width:14px;height:14px;border-radius:50%;display:inline-block;margin:8px;opacity:.3;transition:opacity .2s ease}"
".led.red{background:var(--red)}.led.green{background:var(--green)}.on{opacity:1}"
".val{font-size:clamp(28px,8vw,42px);font-weight:900;text-shadow:0 2px 5px rgba(0,0,0,.1)}"
".val.cur{color:#e53935}.val.set{color:#1a73e8}"
".lineBlock{display:inline-block;text-align:left;}"
".subnote{margin-top:-6px;margin-bottom:6px;opacity:.6;font-size:13px;}"
".row{display:flex;gap:var(--gap);margin-top:var(--gap)}.col{display:flex;flex-direction:column;gap:var(--gap)}"
".btn{flex:1;display:flex;align-items:center;justify-content:center;text-decoration:none;font-weight:700;"
"min-height:var(--btnH);border:none;border-radius:var(--r);cursor:pointer;user-select:none;-webkit-user-select:none;"
"color:#fff;font-size:1.05em;box-shadow:inset 0 2px 0 rgba(255,255,255,.3),0 6px 0 rgba(0,0,0,.25),var(--shadow);"
"transition:transform .05s ease,box-shadow .1s ease,filter .1s ease;}"
".btn.red{background:linear-gradient(to bottom,#ff5b5b,#c62828);} "
".btn.green{background:linear-gradient(to bottom,#4caf50,#1b7f2a);} "
".btn.blue{background:linear-gradient(to bottom,#3b82f6,#1557b0);} .btn.orange{background:linear-gradient(to bottom,#ffb347,#e67e22);} "
".btn.gray{background:linear-gradient(to bottom,#777,#444);} "
".btn:active{transform:translateY(3px);box-shadow:inset 0 2px 0 rgba(255,255,255,.3),0 2px 0 rgba(0,0,0,.2);filter:brightness(.92);}"
"</style></head><body>"
"<div class='card'>"
"<h3>HMK 智能控制</h3>"
"<div id='statusBlock' class='statusText'>狀態偵測中...</div>"
"<div id='heatBlock' class='heatText heatWait'>加熱狀態讀取中...</div>"
"<div><span id='ledOn' class='led green'></span><span id='ledOff' class='led red'></span></div>"
"<div class='lineBlock'>"
"<div>顯示溫度：<span id='temp' class='val cur'>--</span> °C</div>"
"</div>"
"<div>設定溫度：<span id='set' class='val set'>--</span> °C</div>"
"<div class='row'><button class='btn green' data-cmd='/tempdown'>－ 溫度降低</button>"
"<button class='btn red' data-cmd='/tempup'>＋ 溫度提高</button></div>"
"<div class='col' style='margin-top:var(--gap)'><button class='btn blue' data-cmd='/poweron'>開機</button>"
"<button class='btn orange' data-cmd='/timermode'>定時</button>"
"<button class='btn gray' data-cmd='/shutdown'>關機</button></div>"
"<div style='opacity:.6;font-size:13px;margin-top:10px'>v2.8f</div>"
"<script>"
"let lock=false;"

// ===== 顯示溫度顯示狀態（只影響手機顯示）=====
"let _d=null,_ls=null,_drop=0,_hold=null,_next=0,_pu=null,_in3=0,_up=0,_upNext=0;"
"function _num(x){let n=Number(x);return Number.isFinite(n)?n:null;}"

"function calcShow(tUpRaw,tSetRaw){"
"  const tUp=_num(tUpRaw), tSet=_num(tSetRaw);"
"  if(tUp===null||tSet===null) return (tUp!==null?tUp:tUpRaw);"
"  const now=Date.now();"
"  const cooled=(_pu!==null && tUp<_pu);"
"  _pu=tUp;"

"  if(_d===null){_d=Math.min(tUp,tSet);_ls=tSet;_hold=_d;_drop=0;_next=0;_in3=0;_up=0;_upNext=0;return _d;}"

"  if(_ls!==null && tSet!==_ls){"
"    const target=Math.min(tUp,tSet);"
"    _drop=0;_next=0;_in3=0;_up=0;_upNext=0;"
"    if(_d>target){"
"      if(tUp>tSet){"
"        _drop=1;_hold=_d;"
"      }else{"
"        _d=tUp;_hold=_d;"
"      }"
"    }else if(_d<target){"
"      _up=1;_upNext=now+30000;"
"    }"
"  }"

"  _ls=tSet;"

"  if(_drop){"
"    if(tUp<=tSet){_drop=0;_next=0;_in3=0;_d=tUp;_hold=_d;return _d;}"
"    const diff=tUp-tSet;"
"    if(diff>3){_in3=0;_next=0;_d=Math.min(_hold,tUp);return _d;}"
"    if(!_in3) _in3=now;"
"    if(cooled && !_next) _in3=now;"
"    if(_d>tUp) _d=tUp;"
"    if(!_next && (now-_in3<30000)) return _d;"

"    if(_d<=tSet){_d=tSet;_drop=0;_next=0;_in3=0;_hold=_d;return _d;}"
"    if(!_next){_d=Math.max(tSet,_d-1);_next=now+30000;}"
"    else if(now>=_next){const steps=Math.floor((now-_next)/30000)+1;_d=Math.max(tSet,_d-steps);_next+=steps*30000;}"
"    if(_d>tUp) _d=tUp;"
"    if(_d<=tSet){_d=tSet;_drop=0;_next=0;_in3=0;_hold=_d;}"
"    return _d;"
"  }"

"  if(_up){"
"    const target=Math.min(tUp,tSet);"
"    if(_d>tUp) _d=tUp;"
"    if(_d>=target){_up=0;_upNext=0;_hold=_d;return _d;}"
"    if(!_upNext) _upNext=now+30000;"
"    if(now>=_upNext){const steps=Math.floor((now-_upNext)/30000)+1;_d=Math.min(target,_d+steps);_upNext+=steps*30000;}"
"    if(_d>tUp) _d=tUp;"
"    if(_d>=target){_up=0;_upNext=0;_hold=_d;}"
"    return _d;"
"  }"

"  _d=Math.min(tUp,tSet);"
"  _hold=_d;"
"  _up=0;_upNext=0;"
"  return _d;"
"}"

"async function cmd(u){if(lock)return;lock=true;try{const r=await fetch(u,{method:'POST'});if(!r.ok){const t=await r.text();alert(t||'操作失敗');return;}}catch(e){alert('操作失敗');}finally{lock=false;}"
"setTimeout(update,700);}"
"function bind(){document.querySelectorAll('[data-cmd]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();cmd(b.dataset.cmd);}));}"
"function showMode(m){const on=document.getElementById('ledOn'),off=document.getElementById('ledOff'),t=document.getElementById('statusBlock');on.classList.remove('on');off.classList.remove('on');if(m===1){on.classList.add('on');t.innerHTML='自動/開機中';t.className='statusText statusOn';}else if(m===2){on.classList.add('on');t.innerHTML='定時中';t.className='statusText statusTimer';}else if(m===0){off.classList.add('on');t.innerHTML='關機中';t.className='statusText statusOff';}}"
"function showHeat(h,v){const e=document.getElementById('heatBlock');if(!v){e.innerHTML='加熱狀態讀取中...';e.className='heatText heatWait';}else if(h){e.innerHTML='🔥 加熱中';e.className='heatText heatOn';}else{e.innerHTML='💤 非加熱';e.className='heatText heatOff';}}"
"async function update(){try{let r=await fetch('/status?_='+(Date.now()),{cache:'no-store'});if(!r.ok)return;let j=await r.json();"
"let tShow=calcShow(j.tUp,j.tSet);"
"document.getElementById('temp').innerHTML=tShow;document.getElementById('set').innerHTML=j.tSet;showMode(j.m);showHeat(!!j.heat,!!j.heatValid);}catch(e){}}"
"setInterval(update,2000);update();bind();"
"</script></div></body></html>");
  return s;
}

#endif
